#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# NODIFY SETUP WIZARD
# ═══════════════════════════════════════════════════════════════
#
# This script helps you configure Nodify for your environment.
# Run: bash setup.sh
#
# ═══════════════════════════════════════════════════════════════

set -e  # Exit on error

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║                 NODIFY SETUP WIZARD                            ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────
# 1. Check Prerequisites
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}[1/6] Checking prerequisites...${NC}"
echo ""

# Check Node.js version
if ! command -v node &> /dev/null; then
    echo -e "${RED}❌ Node.js is not installed${NC}"
    echo "Please install Node.js 18+ from https://nodejs.org/"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
REQUIRED_VERSION=18

if [ "$NODE_VERSION" -lt "$REQUIRED_VERSION" ]; then
    echo -e "${RED}❌ Node.js $REQUIRED_VERSION+ required. Current: v$NODE_VERSION${NC}"
    echo "Please upgrade Node.js from https://nodejs.org/"
    exit 1
fi

echo -e "${GREEN}✅ Node.js v$NODE_VERSION detected${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}❌ npm is not installed${NC}"
    exit 1
fi

NPM_VERSION=$(npm -v)
echo -e "${GREEN}✅ npm v$NPM_VERSION detected${NC}"
echo ""

# ─────────────────────────────────────────────────────────────────
# 2. Create .env.local
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}[2/6] Configuring environment variables...${NC}"
echo ""

if [ -f .env.local ]; then
    echo -e "${YELLOW}⚠️  .env.local already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Skipping .env.local creation"
        ENV_SKIPPED=true
    else
        rm .env.local
    fi
fi

if [ "$ENV_SKIPPED" != "true" ]; then
    echo "Let's configure your Firebase and API keys."
    echo ""

    # Webhook Secret
    echo -e "${BLUE}Generating security secrets...${NC}"
    WEBHOOK_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    CRON_SECRET=$(openssl rand -base64 32 | tr -d '\n')
    echo -e "${GREEN}✅ Generated webhook and cron secrets${NC}"
    echo ""

    # Firebase Config
    echo -e "${BLUE}Firebase Configuration${NC}"
    echo "Get these from: Firebase Console → Project Settings → Your apps → Web app"
    echo ""

    read -p "Firebase API Key: " FIREBASE_API_KEY
    read -p "Firebase Auth Domain (e.g., project-id.firebaseapp.com): " FIREBASE_AUTH_DOMAIN
    read -p "Firebase Project ID: " FIREBASE_PROJECT_ID
    read -p "Firebase Storage Bucket (e.g., project-id.appspot.com): " FIREBASE_STORAGE_BUCKET
    read -p "Firebase Messaging Sender ID: " FIREBASE_MESSAGING_SENDER_ID
    read -p "Firebase App ID: " FIREBASE_APP_ID

    echo ""
    echo -e "${BLUE}Firebase Admin (Service Account)${NC}"
    echo "Get from: Firebase Console → Project Settings → Service Accounts → Generate new private key"
    echo ""
    echo "Have you downloaded the service account JSON file? (y/N)"
    read -p "> " -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        read -p "Path to service account JSON file: " SERVICE_ACCOUNT_PATH
        if [ -f "$SERVICE_ACCOUNT_PATH" ]; then
            FIREBASE_SERVICE_ACCOUNT_BASE64=$(cat "$SERVICE_ACCOUNT_PATH" | base64 -w 0 2>/dev/null || cat "$SERVICE_ACCOUNT_PATH" | base64)
            echo -e "${GREEN}✅ Service account loaded and encoded${NC}"
        else
            echo -e "${RED}❌ File not found: $SERVICE_ACCOUNT_PATH${NC}"
            echo "Skipping service account configuration - you'll need to add it manually"
            FIREBASE_SERVICE_ACCOUNT_BASE64=""
        fi
    else
        echo "Skipping service account - you'll need to add FIREBASE_SERVICE_ACCOUNT_BASE64 manually"
        FIREBASE_SERVICE_ACCOUNT_BASE64=""
    fi

    echo ""
    echo -e "${BLUE}Google Gemini AI${NC}"
    echo "Get API key from: https://makersuite.google.com/app/apikey"
    echo ""
    read -p "Gemini API Key (or press Enter to skip): " GEMINI_API_KEY

    # Create .env.local
    cat > .env.local << EOF
# ═══════════════════════════════════════════════════════════════
# NODIFY ENVIRONMENT CONFIGURATION
# Generated by setup.sh on $(date)
# ═══════════════════════════════════════════════════════════════

# Webhooks & Security
WEBHOOK_SECRET_TOKEN=$WEBHOOK_SECRET
CRON_SECRET=$CRON_SECRET

# Firebase Client Configuration
NEXT_PUBLIC_FIREBASE_API_KEY=$FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$FIREBASE_APP_ID

# Firebase Admin (Server-side)
FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
FIREBASE_SERVICE_ACCOUNT_BASE64=$FIREBASE_SERVICE_ACCOUNT_BASE64

# Google AI (Gemini)
GEMINI_API_KEY=$GEMINI_API_KEY

# ═══════════════════════════════════════════════════════════════
# OPTIONAL CONFIGURATION
# See .env.example for more options (email, analytics, etc.)
# ═══════════════════════════════════════════════════════════════
EOF

    echo -e "${GREEN}✅ .env.local created successfully${NC}"
    echo ""
fi

# ─────────────────────────────────────────────────────────────────
# 3. Install Dependencies
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}[3/6] Installing dependencies...${NC}"
echo "This may take a few minutes..."
echo ""

npm ci

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Dependencies installed${NC}"
else
    echo -e "${RED}❌ Failed to install dependencies${NC}"
    exit 1
fi
echo ""

# ─────────────────────────────────────────────────────────────────
# 4. Firebase Setup Reminder
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}[4/6] Firebase setup checklist...${NC}"
echo ""
echo "Make sure you've completed these Firebase steps:"
echo ""
echo -e "${BLUE}☐${NC} Created Firebase project"
echo -e "${BLUE}☐${NC} Enabled Authentication (Email/Password provider)"
echo -e "${BLUE}☐${NC} Created Firestore database"
echo -e "${BLUE}☐${NC} Enabled Storage"
echo -e "${BLUE}☐${NC} Deployed security rules: firebase deploy --only firestore:rules"
echo ""
read -p "Press Enter to continue..."
echo ""

# ─────────────────────────────────────────────────────────────────
# 5. Build Application
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}[5/6] Building application...${NC}"
echo "This will verify everything is configured correctly..."
echo ""

npm run build

if [ $? -eq 0 ]; then
    echo -e "${GREEN}✅ Build successful${NC}"
else
    echo -e "${RED}❌ Build failed${NC}"
    echo "Please check the error messages above and fix any issues"
    echo "Common issues:"
    echo "  - Missing environment variables in .env.local"
    echo "  - TypeScript errors in custom code"
    exit 1
fi
echo ""

# ─────────────────────────────────────────────────────────────────
# 6. Summary & Next Steps
# ─────────────────────────────────────────────────────────────────
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    SETUP COMPLETE! 🎉                          ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo ""
echo -e "  ${GREEN}1.${NC} Start development server:"
echo -e "     ${YELLOW}npm run dev${NC}"
echo ""
echo -e "  ${GREEN}2.${NC} Open your browser:"
echo -e "     ${YELLOW}http://localhost:9003${NC}"
echo ""
echo -e "  ${GREEN}3.${NC} Create your first user account (will be stored in Firebase)"
echo ""
echo -e "  ${GREEN}4.${NC} (Optional) Make first user admin:"
echo -e "     - Go to Firebase Console → Firestore"
echo -e "     - Find your user document in 'users' collection"
echo -e "     - Add field: ${YELLOW}role${NC} = ${YELLOW}super_admin${NC}"
echo ""
echo -e "${BLUE}For production deployment:${NC}"
echo -e "  - Read ${YELLOW}DEPLOYMENT.md${NC} for detailed instructions"
echo -e "  - Run ${YELLOW}npm start${NC} after building"
echo ""
echo -e "${BLUE}Need help?${NC}"
echo -e "  - Documentation: ${YELLOW}./docs/${NC}"
echo -e "  - Troubleshooting: ${YELLOW}DEPLOYMENT.md${NC}"
echo ""
echo -e "${GREEN}Happy automating! 🚀${NC}"
echo ""
